[2023-01-28 01:10:17,124] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2023-01-28 01:10:17,133] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2023-01-28 01:10:17,135] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:10:17,136] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:10:17,137] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:10:17,153] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-10-01 00:00:00+00:00
[2023-01-28 01:10:17,158] {standard_task_runner.py:52} INFO - Started process 2614 to run task
[2023-01-28 01:10:17,162] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpns2kz801', '--error-file', '/tmp/tmpd8unqpgv']
[2023-01-28 01:10:17,163] {standard_task_runner.py:77} INFO - Job 102: Subtask local_to_gcs_task
[2023-01-28 01:10:17,226] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:10:17,270] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:10:17,290] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-10-01T00:00:00+00:00
[2023-01-28 01:11:51,243] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:11:51,265] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191001T000000, start_date=20230128T011017, end_date=20230128T011151
[2023-01-28 01:11:51,315] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:11:51,351] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:46:20,089] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:20,109] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [queued]>
[2023-01-29 12:46:20,110] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:20,111] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:46:20,112] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:46:20,125] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-10-01 00:00:00+00:00
[2023-01-29 12:46:20,131] {standard_task_runner.py:52} INFO - Started process 7619 to run task
[2023-01-29 12:46:20,135] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-10-01T00:00:00+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpk33ujag_', '--error-file', '/tmp/tmp6_a8vv9x']
[2023-01-29 12:46:20,137] {standard_task_runner.py:77} INFO - Job 421: Subtask local_to_gcs_task
[2023-01-29 12:46:20,217] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-10-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:46:20,293] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:46:20,322] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-10-01T00:00:00+00:00
[2023-01-29 12:46:31,591] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:46:31,604] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191001T000000, start_date=20230129T124620, end_date=20230129T124631
[2023-01-29 12:46:31,636] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:46:31,671] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
