[2023-01-28 01:12:21,753] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2023-01-28 01:12:21,763] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2023-01-28 01:12:21,764] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:12:21,764] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-28 01:12:21,765] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-28 01:12:21,775] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-12-01 00:00:00+00:00
[2023-01-28 01:12:21,781] {standard_task_runner.py:52} INFO - Started process 2896 to run task
[2023-01-28 01:12:21,784] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp9zpi_399', '--error-file', '/tmp/tmprmee98gm']
[2023-01-28 01:12:21,786] {standard_task_runner.py:77} INFO - Job 107: Subtask local_to_gcs_task
[2023-01-28 01:12:21,847] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [running]> on host adbf820de9e6
[2023-01-28 01:12:21,890] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-28 01:12:21,909] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-01T00:00:00+00:00
[2023-01-28 01:13:22,130] {python.py:175} INFO - Done. Returned value was: None
[2023-01-28 01:13:22,147] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191201T000000, start_date=20230128T011221, end_date=20230128T011322
[2023-01-28 01:13:22,179] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-28 01:13:22,219] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-29 12:47:24,160] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2023-01-29 12:47:24,170] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [queued]>
[2023-01-29 12:47:24,171] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:47:24,172] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-01-29 12:47:24,173] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-01-29 12:47:24,183] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-12-01 00:00:00+00:00
[2023-01-29 12:47:24,189] {standard_task_runner.py:52} INFO - Started process 7862 to run task
[2023-01-29 12:47:24,193] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-12-01T00:00:00+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmptt55t64k', '--error-file', '/tmp/tmp3epcho0g']
[2023-01-29 12:47:24,194] {standard_task_runner.py:77} INFO - Job 430: Subtask local_to_gcs_task
[2023-01-29 12:47:24,253] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-12-01T00:00:00+00:00 [running]> on host 2530f37057aa
[2023-01-29 12:47:24,301] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-01-29 12:47:24,329] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-01T00:00:00+00:00
[2023-01-29 12:47:36,834] {python.py:175} INFO - Done. Returned value was: None
[2023-01-29 12:47:36,850] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20191201T000000, start_date=20230129T124724, end_date=20230129T124736
[2023-01-29 12:47:36,896] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-01-29 12:47:36,929] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
